#!/usr/bin/env bash

set -e
[ -n "$GOENV_DEBUG" ] && set -x

# Remove goenv-goget-rehash/libexec from PATH to avoid infinite loops in `goenv-which`
_PATH=":${PATH}:"
_HERE="$(dirname "${BASH_SOURCE[0]}")" # remove this from PATH
_PATH="${_PATH//:${_HERE}:/:}"
_PATH="${_PATH#:}"
_PATH="${_PATH%:}"
PATH="${_PATH}"

GOENV_COMMAND_PATH="$(goenv-which "$(basename "$0")")"
GOENV_BIN_PATH="${GOENV_COMMAND_PATH%/*}"

export PATH="${GOENV_BIN_PATH}:${PATH}"

STATUS=0
"$GOENV_COMMAND_PATH" "$@" || STATUS="$?"

# Run `goenv-rehash` after a successful installation.
if [ "$STATUS" == "0" ]; then
  case "$1" in
  "get" ) goenv-rehash;;
  esac
fi

exit "$STATUS"